/* DO NOT EDIT, file generated by nestjs-i18n */

/* eslint-disable */
/* prettier-ignore */
import { Path } from "nestjs-i18n";
/* prettier-ignore */
export type I18nTranslations = {
    "common": {
        "internal_server_error": string;
        "invalid_request": string;
    };
    "migrations": {
        "admin_account_already_exists": string;
        "admin_account_created": string;
    };
    "users": {
        "user_with_email_exists": string;
        "user_not_exists": string;
    };
    "validation": {
        "email": string;
        "email_is_required": string;
        "password": string;
        "password_is_required": string;
        "first_name_is_required": string;
        "last_name_is_required": string;
        "role_is_required": string;
        "role_must_be": string;
        "current_password_is_required": string;
    };
};
/* prettier-ignore */
export type I18nPath = Path<I18nTranslations>;
